export enum _type_generator_schema {
  'GEN_COMPONENT' = 'GENERATOR_COMPONENT',
  'FRONTEND_SCHEMA_WILL_BE_USE' = 'FRONTEND_SCHEMA_WILL_BE_USE',
  'GEN_HOOK' = 'GENERATOR_HOOK',
  'GEN_CONTEXT' = 'GENERATOR_CONTEXT',
  'GEN_REDUCER_WITH_CONTEXT' = 'GENERATOR_REDUCER_WITH_CONTEXT',
  'GEN_TYPE_CSS_USE' = 'GEN_TYPE_CSS_USE',
}
